#! /bin/sh

nitrogen --restore &

$HOME/.config/polybar/launch.sh

killall picom
picom --experimental-backends &

killall udiskie
udiskie &

killall mpd
mpd &

killall dunst
dunst &

/usr/lib/polkit-kde-authentication-agent-1 &

setxkbmap -option caps:swapescape

xset s off -dpms

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#2aa198"
bspc config normal_border_color	 "#073642"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
